services:
  # auth:
  #   build: ./services/auth
  #   ports:
  #     - "3001:3000"
  #   networks:
  #     - backend
  #   restart: unless-stopped

  # documentation:
  #   build: ./services/documentation
  #   ports:
  #     - "3002:3000"
  #   networks:
  #     - backend
  #   restart: unless-stopped

  language-parser:
    build: ./services/language-parser
    platform: linux/arm64
    ports:
      - "3003:3000"
    volumes:
      - ./services/language-parser:/app
    networks:
      - backend
    restart: unless-stopped
    command: air

  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: none
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - $HOME/code/neo4j/data:/data
      - $HOME/code/neo4j/logs:/logs
      - $HOME/code/neo4j/import:/import
      - $HOME/code/neo4j/plugins:/plugins
      - $HOME/code/neo4j/conf:/conf
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
