version: '3.8'
services:
  # auth:
  #   build: ./services/auth
  #   ports:
  #     - "3001:3000"
  #   networks:
  #     - backend
  #   restart: unless-stopped

  # documentation:
  #   build: ./services/documentation
  #   ports:
  #     - "3002:3000"
  #   networks:
  #     - backend
  #   restart: unless-stopped

  code-analysis:
    build: ./services/code-analysis
    ports:
      - "3003:3000"
    volumes:
      - ./services/code-analysis:/usr/src/app
    networks:
      - backend
    restart: unless-stopped

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - auth
  #     - documentation
  #     - code-analysis
  #   networks:
  #     - backend
  #   restart: unless-stopped

networks:
  backend:
    driver: bridge
