version: '3.8'
services:
  # auth:
  #   build: ./services/auth
  #   ports:
  #     - "3001:3000"
  #   networks:
  #     - backend
  #   restart: unless-stopped

  # documentation:
  #   build: ./services/documentation
  #   ports:
  #     - "3002:3000"
  #   networks:
  #     - backend
  #   restart: unless-stopped

  code-analysis:
    build: ./services/code-analysis
    ports:
      - "3003:3000"
    volumes:
      - ./services/code-analysis:/usr/src/app
    networks:
      - backend
    restart: unless-stopped

  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: none
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/plugins
    networks:
      - backend
    restart: unless-stopped

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - auth
  #     - documentation
  #     - code-analysis
  #   networks:
  #     - backend
  #   restart: unless-stopped

networks:
  backend:
    driver: bridge
